// File generated by FlutterFire configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfL_ciB0Wb8LvcEaK1jrq34-ISzPIcAE',
    appId: '1:95756363883:android:d701e7d42e6ef59c1b692e',
    messagingSenderId: '95756363883',
    projectId: 'fixly-fbe31',
    storageBucket: 'fixly-fbe31.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsfL_ciB0Wb8LvcEaK1jrq34-ISzPIcAE',
    appId: '1:95756363883:web:fixly',
    messagingSenderId: '95756363883',
    projectId: 'fixly-fbe31',
    storageBucket: 'fixly-fbe31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsfL_ciB0Wb8LvcEaK1jrq34-ISzPIcAE',
    appId: '1:95756363883:ios:fixly',
    messagingSenderId: '95756363883',
    projectId: 'fixly-fbe31',
    storageBucket: 'fixly-fbe31.firebasestorage.app',
  );
}
